apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../base
  - hpa.yaml              # extra manifest, merged with the helm output

namespace: podinfo-prod

patches:
  - target: {kind: Deployment, name: podinfo}
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "environment: production"
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "#c62828"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "128Mi"
